In [1]:
from qiskit import Aer
from qiskit.aqua.algorithms import VQE, ExactEigensolver, QAOA
from qiskit.aqua.components.optimizers import SPSA
from qiskit.aqua import QuantumInstance
from qiskit.aqua import aqua_globals
from qiskit.circuit.library import RealAmplitudes
from qiskit.visualization import circuit_visualization
from docplex.mp.model import Model
from qiskit.optimization.applications.ising import docplex
# from qiskit import IBMQ
# IBMQ.load_account()
import numpy as np

from collections import OrderedDict

In [2]:
M = [2,6,3]
K = [1,4,2]
T = [12, 6, 24]
d = 19

def get_time_matrix(M, T):
    r = []
    for i in M:
        tmp = []
        for j in T:
            tmp.append(j / i)
        r.append(tmp)
    return np.array(r)


def get_cost_matrix(time_matrix, K):
    m = []
    for i in range(len(time_matrix)):
        tmp = []
        for j in time_matrix[i]:
            tmp.append(K[i] * j)
        m.append(tmp)
    return m

time_matrix = np.array(get_time_matrix(M, T))
cost_matrix = np.array(get_cost_matrix(time_matrix, K))

print("Time matrix:\n {}".format(time_matrix))
print("Cost matrix:\n {}".format(cost_matrix))

Time matrix:
 [[ 6.  3. 12.]
 [ 2.  1.  4.]
 [ 4.  2.  8.]]
Cost matrix:
 [[ 6.  3. 12.]
 [ 8.  4. 16.]
 [ 8.  4. 16.]]


In [3]:
def sample_most_likely(state_vector):
    if isinstance(state_vector, (OrderedDict, dict)):
        # get the binary string with the largest count
        binary_string = sorted(state_vector.items(), key=lambda kv: kv[1])
        repetitions = int(binary_string[-1][1])
        binary_string = binary_string[-1][0]
        x = np.asarray([int(y) for y in reversed(list(binary_string))])
        return x, repetitions
    return [], 0

optimal_key = "0000011001"

def get_stats_for_result(dict_res):
    optimal = 0
    correct = 0
    incorrect = 0
    correct_config = 0
    incorrect_config = 0
     
    if optimal_key in dict_res:
        optimal = dict_res[optimal_key]
    for key, val in dict_res.items():
        if is_correct(key):
            correct += val
            correct_config += 1
        else:
            incorrect += val
            incorrect_config += 1
            
    print('most likely solution: ',sample_most_likely(dict_res))      
    print("optimal: ", optimal)
    print("correct solutions: ", correct)
    print("incorrect solutions: ", incorrect)
    print("correct configs: ", correct_config)
    print("incorrect configs: ", incorrect_config)

def is_correct(key):
    reversed_key = key[::-1]
    if solution_vector_correct(reversed_key) and execution_time(reversed_key) <= d:
        return True
    return False

correct_machines = ['00', '01', '10']
machine_to_index = {'00': 0, '01': 1, '10': 2}

def solution_vector_correct(vector):
    task1_machine = vector[0:2]
    task2_machine = vector[2:4]
    task3_machine = vector[4:6]

    if task1_machine in correct_machines and task2_machine in correct_machines and task3_machine in correct_machines:
        return True
    return False

def execution_time(k):
    task1_machine = machine_to_index.get(k[0:2])
    task2_machine = machine_to_index.get(k[2:4])
    task3_machine = machine_to_index.get(k[4:6])
    
    task1_time = time_matrix[task1_machine, 0]
    task2_time = time_matrix[task2_machine, 1]
    task3_time = time_matrix[task3_machine, 2]
    
    slack_sum = int(k[6]) * 8 + int(k[7]) * 4 + int(k[8]) * 2 + int(k[9]) * 1
    
    return task1_time + task2_time + task3_time + slack_sum

In [4]:
# Minimalizacja kosztu
def getMdl(A,B,C):
    mdl = Model(name='workflow1')
    x = {(i, j) : mdl.binary_var(name='x_{0}_{1}'.format(i, j)) for i in range(0, 3) for j in range(0, 2)}
    x.update({i : mdl.binary_var(name='x_{0}'.format(i)) for i in range(7, 11)})
    
    objective = A * mdl.sum(
          cost_matrix[2, i] * (1 - x[(i, 0)]) * (1 - x[(i, 1)])
        + cost_matrix[1, i] * (1 - x[(i, 0)]) * x[(i, 1)]
        + cost_matrix[0, i] * x[(i, 0)] * (1 - x[(i, 1)])
        for i in range(0, 3)
    )
    
    mdl.add_constraint(B * mdl.sum(x[(i, 0)] * x[(i, 1)] for i in range(0, 3)) == 0, "machine usage")

    mdl.add_constraint(C * (
        mdl.sum([
              time_matrix[2, i] * (1 - x[(i, 0)]) * (1 - x[(i, 1)])
            + time_matrix[1, i] * (1 - x[(i, 0)]) * x[(i, 1)]
            + time_matrix[0, i] * x[(i, 0)] * (1 - x[(i, 1)])
            for i in range(0, 3)
        ]) 
        + (8 * x[7] + 4 * x[8] + 2 * x[9] + x[10])
    ) == C * d, "deadline")
    
    mdl.minimize(objective)
    H, _ = docplex.get_operator(mdl)
    return H

In [5]:
def compute_eigenvalues():
    from qiskit.aqua.algorithms import NumPyEigensolver
    count = 5
    eigensolver = NumPyEigensolver(qubitOp, count)
    eigensolver_result = eigensolver.compute_eigenvalues()
    print(eigensolver_result.eigenvalues)
    for eigenstate in eigensolver_result.eigenstates:
        print(eigenstate.sample())

In [6]:
seed = 123569
aqua_globals.random_seed = seed
entanglement='full'

reps = 2
max_trials = 1000
shots = 100

A = 1
B = 20
C = 1

qubitOp = getMdl(A, B, C)

In [7]:
compute_eigenvalues()

[-1121.25+0.j -1118.25+0.j -1117.25+0.j -1117.25+0.j -1115.25+0.j]
{'1010111111': 1.0}
{'0010110111': 1.0}
{'1010110011': 1.0}
{'0110111011': 1.0}
{'1100111101': 1.0}


In [8]:
spsa = SPSA(maxiter=max_trials)
ry = RealAmplitudes(qubitOp.num_qubits, reps=reps, entanglement=entanglement)
vqe = VQE(qubitOp, ry, spsa)
# provider= IBMQ.get_provider('ibm-q')
backend = Aer.get_backend('qasm_simulator')
quantum_instance = QuantumInstance(backend,seed_simulator=seed, seed_transpiler=seed, shots=shots)
result = vqe.run(quantum_instance)   
state_vector = result['eigenstate']
get_stats_for_result(state_vector)

most likely solution:  (array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0]), 39)
optimal:  0
correct solutions:  4
incorrect solutions:  96
correct configs:  1
incorrect configs:  14


In [9]:
from qiskit.aqua.algorithms import NumPyEigensolver

eigensolver = NumPyEigensolver(qubitOp, 3)
print(eigensolver.compute_eigenvalues())

{'eigenvalues': array([-1121.25+0.j, -1118.25+0.j, -1117.25+0.j]), 'eigenstates': ListOp([VectorStateFn(Statevector([0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
            dims=(2, 2, 2, 2, 2, 2, 2, 2, 2, 2)), coeff=1.0, is_measurement=False), VectorStateFn(Statevector([0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
            dims=(2, 2, 2, 2, 2, 2, 2, 2, 2, 2)), coeff=1.0, is_measurement=False), VectorStateFn(Statevector([0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
            dims=(2, 2, 2, 2, 2, 2, 2, 2, 2, 2)), coeff=1.0, is_measurement=False)], coeff=1.0, abelian=False)}


In [10]:
vqe.get_optimal_cost()
#qaoa.get_optimal_vector()

-1030.0400000000002

In [11]:
vqe.get_optimal_vector()
#qaoa.get_optimal_vector()

{'0101100000': 2,
 '0101110110': 1,
 '1001100000': 25,
 '1001101000': 1,
 '1001111110': 3,
 '1101100000': 4,
 '0001001000': 1,
 '0001100000': 39,
 '0001100011': 4,
 '0001100100': 1,
 '0001101010': 4,
 '0001110110': 7,
 '0001110111': 2,
 '0001111110': 5,
 '0001111111': 1}