In [1]:
from qiskit import Aer
from qiskit.aqua.algorithms import VQE, ExactEigensolver, QAOA
from qiskit.aqua.components.optimizers import SPSA
from qiskit.aqua import QuantumInstance
from qiskit.aqua import aqua_globals
from qiskit.circuit.library import RealAmplitudes
from qiskit.visualization import circuit_visualization
from docplex.mp.model import Model
from qiskit.optimization.applications.ising import docplex
from qiskit import IBMQ
IBMQ.save_account('9272976c3b881b8346c3a619e97a0229e7189137e50baa0b5648a300d9af2ad30fa26d401b1512203e0502f2b2a33984515936c4b4fca8f4a6a1bbb66de12f85', overwrite=True)
IBMQ.load_account()
import numpy as np

from collections import OrderedDict

/home/julia/.local/lib/python3.6/site-packages/qiskit/providers/ibmq/ibmqfactory.py:192: UserWarning: Timestamps in IBMQ backend properties, jobs, and job results are all now in local time instead of UTC.
  warnings.warn('Timestamps in IBMQ backend properties, jobs, and job results '


In [2]:
M = [2,6,3]
K = [1,4,2]
T = [12, 6, 24]
d = 19

def get_time_matrix(M, T):
    r = []
    for i in M:
        tmp = []
        for j in T:
            tmp.append(j / i)
        r.append(tmp)
    return np.array(r)


def get_cost_matrix(time_matrix, K):
    m = []
    for i in range(len(time_matrix)):
        tmp = []
        for j in time_matrix[i]:
            tmp.append(K[i] * j)
        m.append(tmp)
    return m

time_matrix = np.array(get_time_matrix(M, T))
cost_matrix = np.array(get_cost_matrix(time_matrix, K))

print(time_matrix)
print(cost_matrix)

n1  = np.shape(cost_matrix)[0]
n2 = np.shape(cost_matrix)[1]

[[ 6.  3. 12.]
 [ 2.  1.  4.]
 [ 4.  2.  8.]]
[[ 6.  3. 12.]
 [ 8.  4. 16.]
 [ 8.  4. 16.]]


In [3]:
def sample_most_likely(state_vector):
    if isinstance(state_vector, (OrderedDict, dict)):
        # get the binary string with the largest count
        binary_string = sorted(state_vector.items(), key=lambda kv: kv[1])
        print(binary_string)
        repetitions = int(binary_string[-1][1])
        binary_string = binary_string[-1][0]
        x = np.asarray([int(y) for y in reversed(list(binary_string))])
        return x, repetitions
    return [], 0

optimal_key = "0000001000"
time_limit = 19

def get_stats_for_result(dict_res):
    optimal = 0
    correct = 0
    incorrect = 0
    correct_config = 0
    incorrect_config = 0
     
    if optimal_key in dict_res:
        optimal = dict_res[optimal_key]
    for key, val in dict_res.items():
        if is_correct(key):
            correct += val
            correct_config += 1
        else:
            incorrect += val
            incorrect_config += 1
            
    print('most likely solution: ',sample_most_likely(dict_res))      
    print("optimal: ", optimal)
    print("correct solutions: ", correct)
    print("incorrect solutions: ", incorrect)
    print("correct configs: ", correct_config)
    print("incorrect configs: ", incorrect_config)

def is_correct(key):
    reversed_key = key[::-1]
    if solution_vector_correct(reversed_key) and execution_time(reversed_key) <= time_limit:
        return True
    return False

correct_machines = ['00', '01', '11']
machine_to_index = {'00': 0, '01': 1, '11': 2}

def execution_time(k):
    slack_sum = int(k[6]) * 8 + int(k[7]) * 4 + int(k[8]) * 2 + int(k[9]) * 1
    
    task1_machine = machine_to_index.get(k[0:2])
    task2_machine = machine_to_index.get(k[2:4])
    task3_machine = machine_to_index.get(k[4:6])
    
    # for vector "10" (the only incorrect one), assign sum of all machines times for task
    task_time_sum =  np.sum(time_matrix, axis=0) 
    task1_time = task_time_sum[0] if task1_machine == None else time_matrix[task1_machine, 0]
    task2_time = task_time_sum[1] if task2_machine == None else time_matrix[task2_machine, 1]
    task3_time = task_time_sum[2] if task3_machine == None else time_matrix[task3_machine, 2]
    
    return slack_sum + task1_time + task2_time + task3_time
    
def solution_vector_correct(vector):
    task1_machine = vector[0:2]
    task2_machine = vector[2:4]
    task3_machine = vector[4:6]

    if task1_machine in correct_machines and task2_machine in correct_machines and task3_machine in correct_machines:
        return True
    return False

In [9]:
cost_matrix[2, :]

array([ 8.,  4., 16.])

In [16]:
cost_matrix[2, 2]

16.0

In [ ]:
# Minimalizacja kosztu
def getMdl(A,B,C):
    mdl = Model(name='workflow1')
    x = {(i, j) : mdl.binary_var(name='x_{0}_{1}'.format(i, j)) for i in range(0, 3) for j in range(0, 2)}
    x.update({i : mdl.binary_var(name='x_{0}'.format(i)) for i in range(7, 11)})
    
    objective = A * mdl.sum(
          cost_matrix[2, i] * (1 - x[(i, 0)]) * (1 - x[(i, 1)])
        + cost_matrix[1, i] * (1 - x[(i, 0)]) * x[(i, 1)]
        + cost_matrix[0, i] * x[(i, 0)] * (1 - x[(i, 1)])
        for i in range(0, 3)
    )
    
    mdl.add_constraint(B * mdl.sum(x[(i, 0)] * x[(i, 1)] for i in range(0, 3)) == 0)

    mdl.add_constraint(C * (
        mdl.sum([
              time_matrix[2, i] * (1 - x[(i, 0)]) * (1 - x[(i, 1)])
            + time_matrix[1, i] * (1 - x[(i, 0)]) * x[(i, 1)]
            + time_matrix[0, i] * x[(i, 0)] * (1 - x[(i, 1)])
            for i in range(0, 3)
        ]) 
        + (8 * x[7] + 4 * x[8] + 2 * x[9] + x[10])
    ) == C * d)
    
    mdl.minimize(objective)
    H, _ = docplex.get_operator(mdl)
    return H

In [9]:
write_to_file = False
filename = 'results.txt'

seed = 123569
aqua_globals.random_seed = seed
entanglement='full'

reps = 2
max_trials = 1000
shots = 100

A = 1
B = 20
C = 1

qubitOp = getMdl(A, B, C)


def compute_eigenvalues():
    from qiskit.aqua.algorithms import NumPyEigensolver
    count = 5
    eigensolver = NumPyEigensolver(qubitOp, count)
    eigensolver_result = eigensolver.compute_eigenvalues()
    print(eigensolver_result.eigenvalues)
    for eigenstate in eigensolver_result.eigenstates:
        print(eigenstate.sample())

compute_eigenvalues()


# spsa = SPSA(maxiter=max_trials)
# ry = RealAmplitudes(qubitOp.num_qubits, reps=reps, entanglement=entanglement)
# vqe = VQE(qubitOp, ry, spsa)
# # provider= IBMQ.get_provider('ibm-q')
# backend = Aer.get_backend('qasm_simulator')
# quantum_instance = QuantumInstance(backend,seed_simulator=seed, seed_transpiler=seed, shots=shots)
# result = vqe.run(quantum_instance)   
# state_vector = result['eigenstate']
# get_stats_for_result(state_vector)

[-1121.25+0.j -1118.25+0.j -1117.25+0.j -1117.25+0.j -1115.25+0.j]
{'1010111111': 1.0}
{'0010110111': 1.0}
{'1010110011': 1.0}
{'0110111011': 1.0}
{'1100111101': 1.0}


In [6]:
# vqe.get_optimal_circuit().draw()

In [7]:
vqe.get_optimal_cost()

-968.4800000000004

In [8]:
vqe.get_optimal_vector()

{'0100000001': 10,
 '0100000011': 1,
 '0100000100': 14,
 '0100000110': 1,
 '0100000111': 7,
 '0100001001': 2,
 '0100001011': 2,
 '0100001100': 1,
 '0100001111': 3,
 '0100010000': 1,
 '0100010001': 2,
 '0100010011': 1,
 '0100010100': 6,
 '0100010111': 2,
 '0100011000': 1,
 '0100011100': 1,
 '0100011101': 1,
 '0101101000': 4,
 '0101101001': 1,
 '0101101111': 2,
 '1000011001': 1,
 '1100000111': 2,
 '1100001001': 1,
 '1110000001': 1,
 '1110000100': 1,
 '1110001001': 1,
 '1110001011': 1,
 '0001101000': 3,
 '0001101001': 3,
 '0001101010': 1,
 '0001101011': 1,
 '0001101100': 1,
 '0001101111': 7,
 '0011101000': 5,
 '0011101001': 2,
 '0011101111': 6}